{
  "formatVersion": "1.1",
  "component": {
    "group": "com.outbrain.mobile",
    "module": "obsdk",
    "version": "4.26.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "obsdk-4.26.1.aar",
          "url": "obsdk-4.26.1.aar",
          "size": 381522,
          "sha512": "6a89732b171bb347459c22f241dcbba4bafd073d885df0d5e20eb5e6c71945f0eed3830c3136a27ebe73a6751e7bf90cccd0287aa273ba8edaa6af77f173694b",
          "sha256": "7054424ab8e50120f24264b34aaee1ac79d6e6d286544137bb2afbd493c2a7c2",
          "sha1": "8acf6c7ff1ebe5383cf7d8e3f2e3cd30a2db49c6",
          "md5": "cfd9ed7e4f4ecb3c7eda4e6b412bb4cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.outbrain",
          "module": "discrete-scrollview",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.outbrain",
          "module": "pageindicatorview",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "otto",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "obsdk-4.26.1.aar",
          "url": "obsdk-4.26.1.aar",
          "size": 381522,
          "sha512": "6a89732b171bb347459c22f241dcbba4bafd073d885df0d5e20eb5e6c71945f0eed3830c3136a27ebe73a6751e7bf90cccd0287aa273ba8edaa6af77f173694b",
          "sha256": "7054424ab8e50120f24264b34aaee1ac79d6e6d286544137bb2afbd493c2a7c2",
          "sha1": "8acf6c7ff1ebe5383cf7d8e3f2e3cd30a2db49c6",
          "md5": "cfd9ed7e4f4ecb3c7eda4e6b412bb4cf"
        }
      ]
    }
  ]
}
