{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zendesk",
    "module": "support",
    "version": "5.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.zendesk",
          "module": "guide",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "messaging",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "sdk-configurations",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "support-providers",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "support-5.2.0.aar",
          "url": "support-5.2.0.aar",
          "size": 763541,
          "sha512": "e31f8b6ec098b62da48c003401ee0adf9943a79cccd59e3a1e3a2a0af3c15b91764a9255b747c816f09506977536bf94cd7931a1987915c8e93a07a79b98fcab",
          "sha256": "4b48ae61c486b196988c3f7b32f252a1b0ab493df3c37d49647d587f2bea6d84",
          "sha1": "ffa8600533c27e182f5aa87102e21c97184e940f",
          "md5": "2e23b62ea5fbeac79309aa42aebfb60c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.zendesk",
          "module": "guide",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "messaging",
          "version": {
            "requires": "5.4.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "sdk-configurations",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.zendesk",
          "module": "support-providers",
          "version": {
            "requires": "5.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger-android",
          "version": {
            "requires": "2.42"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "disklrucache",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.zendesk.belvedere2",
          "module": "belvedere",
          "version": {
            "requires": "3.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "support-5.2.0.aar",
          "url": "support-5.2.0.aar",
          "size": 763541,
          "sha512": "e31f8b6ec098b62da48c003401ee0adf9943a79cccd59e3a1e3a2a0af3c15b91764a9255b747c816f09506977536bf94cd7931a1987915c8e93a07a79b98fcab",
          "sha256": "4b48ae61c486b196988c3f7b32f252a1b0ab493df3c37d49647d587f2bea6d84",
          "sha1": "ffa8600533c27e182f5aa87102e21c97184e940f",
          "md5": "2e23b62ea5fbeac79309aa42aebfb60c"
        }
      ]
    }
  ]
}
