{
  "formatVersion": "1.1",
  "component": {
    "group": "com.outbrain.mobile",
    "module": "obsdk",
    "version": "4.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "obsdk-4.23.0.aar",
          "url": "obsdk-4.23.0.aar",
          "size": 377425,
          "sha512": "a393e41ded7b0d2063158d3726158dd8d2acecd5347532424b31423026c7e4b5a36e9301b87670e4d98608bbfe63bf2574f40c13bf5076877a1a500a55a01b04",
          "sha256": "e6f8407217610fa606b2f9db262bb5d13a2d5fe48bb34f4a8931b9ea80ee7f5b",
          "sha1": "567fb3817e84f64dde78b86f53f76dabde2e379b",
          "md5": "fd92de58c02c69964be95859416ee4be"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.outbrain",
          "module": "discrete-scrollview",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "com.outbrain",
          "module": "pageindicatorview",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-bom",
          "version": {
            "requires": "4.10.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.squareup",
          "module": "otto",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.6"
          }
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "pl.droidsonroids.gif",
          "module": "android-gif-drawable",
          "version": {
            "requires": "1.2.25"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.1.0"
          }
        },
        {
          "group": "com.googlecode.json-simple",
          "module": "json-simple",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "obsdk-4.23.0.aar",
          "url": "obsdk-4.23.0.aar",
          "size": 377425,
          "sha512": "a393e41ded7b0d2063158d3726158dd8d2acecd5347532424b31423026c7e4b5a36e9301b87670e4d98608bbfe63bf2574f40c13bf5076877a1a500a55a01b04",
          "sha256": "e6f8407217610fa606b2f9db262bb5d13a2d5fe48bb34f4a8931b9ea80ee7f5b",
          "sha1": "567fb3817e84f64dde78b86f53f76dabde2e379b",
          "md5": "fd92de58c02c69964be95859416ee4be"
        }
      ]
    }
  ]
}
